server:
  port: 8081
#jdbc
spring:
  datasource:
   # url: jdbc:mysql://192.168.47.128:3306/heima29
    url: jdbc:mysql://192.168.142.130:3306/heima29
    username: root
    password: 123456
#mybatis
mybatis:
  type-aliases-package: cn.itcast.pojo
   #扫描mybatis xml sql 语句文件
   mapper-locations: classpath:mapper/*.xml
  # mapper-locations: classpath*:cn/itcast/mappers/*.xml
    #扫描核心包
   #config-location: classpath:



